/****** Object:  Database [Prod]    Script Date: 15.11.2018 12:46:02 ******/
CREATE DATABASE [Prod]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Prod', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.NEW\MSSQL\DATA\Prod_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [secondary] 
( NAME = N'secondary_786DCA03', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.NEW\MSSQL\DATA\Prod_secondary_786DCA03.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Prod_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.NEW\MSSQL\DATA\Prod_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Prod] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Prod].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Prod] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [Prod] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Prod] SET ANSI_PADDING ON 
GO
ALTER DATABASE [Prod] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [Prod] SET ARITHABORT ON 
GO
ALTER DATABASE [Prod] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Prod] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Prod] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Prod] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Prod] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [Prod] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [Prod] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Prod] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [Prod] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Prod] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Prod] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Prod] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Prod] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Prod] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Prod] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Prod] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Prod] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Prod] SET RECOVERY FULL 
GO
ALTER DATABASE [Prod] SET  MULTI_USER 
GO
ALTER DATABASE [Prod] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [Prod] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Prod] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Prod] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Prod] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Prod', N'ON'
GO
ALTER DATABASE [Prod] SET QUERY_STORE = OFF
GO
